dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [

    path('', include('aurora.urls', namespace='aurora')),

    path('admin/', admin.site.urls),
    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('change-password/',
    #     auth_views.PasswordChangeView.as_view(template_name='zenix/change-password.html',
    #                                           success_url='/users/'),
    #     name='change-password'
    # ),
    path('password/', users_views.change_password, name='change_password'),

    # data
    path('data/', include('data.urls', namespace='data')),

    # operation
    path("operation/", include('operation.urls', namespace='operation')),

    # administrator
    path("administrator/", include('users.urls', namespace='administrator')),
]

if settings.DEBUG == True or settings.DEBUG == False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"


'''
1- Submit email form                           PasswordResetView.as_view()
2- Email sent success Message                  PasswordResetDoneView.as_view()
3- Link to password Rest form in email         PasswordResetConfirmView.as_view()
4- Password successfully changed message       PasswordResetCompleteView.as_view()

'''

data/urls.py
from data import data_views
from django.urls import path

app_name = 'data'

urlpatterns = [
    path("svc-user-status-daily/", data_views.svc_user_status_daily, name="svc-user-status-daily"),
    path("svc-user-status-month/", data_views.svc_user_status_month, name="svc-user-status-month"),
    path("svc-activity-user/", data_views.svc_activity_user, name="svc-activity-user"),
    path("scan-status-daily/", data_views.scan_status_daily, name="scan-status-daily"),
    path("scan-status-month/", data_views.scan_status_month, name="scan-status-month"),
    path("scan-activity-status/", data_views.scan_activity_status, name="scan-activity-status"),
    path('download-summary-as-csv-user-daily/', data_views.download_summary_as_csv_user_daily, name='download-summary-as-csv-user-daily'),
    path('download-summary-as-csv-user-month/', data_views.download_summary_as_csv_user_month, name='download-summary-as-csv-user-month'),
    path('download-summary-as-csv-active-user/', data_views.download_summary_as_csv_active_user, name='download-summary-as-csv-active-user'),
    path('download-summary-as-csv-scan-daily/', data_views.download_summary_as_csv_scan_daily, name='download-summary-as-csv-scan-daily'),
    path('download-summary-as-csv-scan-month/', data_views.download_summary_as_csv_scan_month, name='download-summary-as-csv-scan-month'),
    path('download-summary-as-csv-active-scan/', data_views.download_summary_as_csv_active_scan, name='download-summary-as-csv-active-scan'),
    #path("scan-status/", data_views.scan_status, name="scan-status"),
]

operation/urls.py
from operation import operation_views
from django.urls import path, re_path

app_name = "operation"

urlpatterns = [
    path("svc-user-list/", operation_views.svc_user_list, name="svc-user-list"),
    path("content-list/", operation_views.content_list, name="content-list"),
    path("report-list/", operation_views.report_list, name="report-list"),
    # 이용자 관리
    path("user-management/", operation_views.user_management, name="user-management"),
    re_path(
        r"^user-management/account-id-detail/(?P<account_id>[\w-]+)/$",
        operation_views.accountid_detail,
        name="user-management-account-id-detail",
    ),
    # 사물관리
    path("object-list/", operation_views.object_list, name="object-list"),
    re_path(
        r"^object-list/(?P<object_type>mg_id|scan_id|user_id)/$",
        operation_views.object_list,
        name="object-list-dynamic",
    ),
    re_path(
        r"^object-list/mg-id-detail/(?P<mg_id>[\w\W]+)/$",
        operation_views.mgid_detail,
        name="object-list-mg-id-detail",
    ),
    re_path(
        r"^object-list/scan-id-detail/(?P<scan_id>[\w-]+)/$",
        operation_views.scanid_detail,
        name="object-list-scan-id-detail",
    ),
    re_path(
        r"^object-list/user-id-detail/(?P<user_id>[\w-]+)/$",
        operation_views.userid_detail,
        name="object-list-user-id-detail",
    ),
    # new mg_id
    path("new-mg-id/", operation_views.new_mgid, name="new-mg-id"),
    re_path(
        r"^new-mg-id/(?P<scan_id>[\w\W]+)/$",
        operation_views.new_mgid_detail,
        name="new-mg-id-detail",
    ),
]

operation/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


# hippo
class Brand(models.Model):
    brand_id = models.CharField(primary_key=True, max_length=255)
    brand_name = models.CharField(max_length=255, blank=True, null=True)
    brand_image_url = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "brand"


class FlywaySchemaHistory(models.Model):
    installed_rank = models.IntegerField(primary_key=True)
    version = models.CharField(max_length=50, blank=True, null=True)
    description = models.CharField(max_length=200)
    type = models.CharField(max_length=20)
    script = models.CharField(max_length=1000)
    checksum = models.IntegerField(blank=True, null=True)
    installed_by = models.CharField(max_length=100)
    installed_on = models.DateTimeField()
    execution_time = models.IntegerField()
    success = models.BooleanField()

    class Meta:
        managed = False
        db_table = "flyway_schema_history"


class Goods(models.Model):
    goods_id = models.CharField(primary_key=True, max_length=255)
    goods_name = models.CharField(max_length=255, blank=True, null=True)
    goods_desc = models.CharField(max_length=255, blank=True, null=True)
    goods_img = models.CharField(max_length=255, blank=True, null=True)
    goods_price = models.IntegerField(blank=True, null=True)
    goods_ref = models.CharField(max_length=255, blank=True, null=True)
    goods_category = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    mg_id = models.CharField(max_length=255, blank=True, null=True)
    discount_price = models.IntegerField(blank=True, null=True)
    discount_flag = models.BooleanField(blank=True, null=True)
    ci_logo = models.CharField(max_length=255, blank=True, null=True)
    middle_category = models.CharField(max_length=255, blank=True, null=True)
    small_category = models.CharField(max_length=255, blank=True, null=True)
    relation_goods = models.JSONField(blank=True, null=True)
    sku = models.IntegerField(blank=True, null=True)
    media_list = models.JSONField(blank=True, null=True)
    brand_color = models.CharField(max_length=255, blank=True, null=True)
    goods_price_str = models.CharField(max_length=255, blank=True, null=True)
    discount_price_str = models.CharField(max_length=255, blank=True, null=True)
    partner_name = models.CharField(max_length=255, blank=True, null=True)
    brand_id = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "goods"


class GoodsProductRelation(models.Model):
    gpr_id = models.BigAutoField(primary_key=True)
    goods_id = models.CharField(max_length=255, blank=True, null=True)
    product_id = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "goods_product_relation"


class ImageRecognition(models.Model):
    mg_id = models.CharField(primary_key=True, max_length=255)
    first_scan_id = models.CharField(max_length=255, blank=True, null=True)
    first_user_id = models.CharField(max_length=255, blank=True, null=True)
    add_info = models.JSONField(blank=True, null=True)
    like_cnt = models.BigIntegerField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "image_recognition"


class ScanInfo(models.Model):
    scan_id = models.CharField(primary_key=True, max_length=255)
    mg_id = models.CharField(max_length=255, blank=True, null=True)
    img_url = models.CharField(max_length=255, blank=True, null=True)
    crop_img_url = models.CharField(max_length=255, blank=True, null=True)
    meta_data = models.JSONField(blank=True, null=True)
    user_id = models.CharField(max_length=255, blank=True, null=True)
    geohash = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    status_flag = models.SmallIntegerField(blank=True, null=True)
    img_name = models.CharField(max_length=255, blank=True, null=True)
    enc_geo = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "scan_info"


class ScanLike(models.Model):
    sl_id = models.BigAutoField(primary_key=True)
    mg_id = models.CharField(max_length=255, blank=True, null=True)
    scan_id = models.CharField(max_length=255, blank=True, null=True)
    user_id = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "scan_like"


# Lama
class Block(models.Model):
    block_id = models.BigAutoField(primary_key=True)
    created_at = models.DateTimeField()
    deleted_at = models.DateTimeField(blank=True, null=True)
    user_id = models.UUIDField(blank=True, null=True)
    blocked_user_id = models.UUIDField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "block"


class FlywaySchemaHistory(models.Model):
    installed_rank = models.IntegerField(primary_key=True)
    version = models.CharField(max_length=50, blank=True, null=True)
    description = models.CharField(max_length=200)
    type = models.CharField(max_length=20)
    script = models.CharField(max_length=1000)
    checksum = models.IntegerField(blank=True, null=True)
    installed_by = models.CharField(max_length=100)
    installed_on = models.DateTimeField()
    execution_time = models.IntegerField()
    success = models.BooleanField()

    class Meta:
        managed = False
        db_table = "flyway_schema_history"


class Follow(models.Model):
    follow_id = models.BigAutoField(primary_key=True)
    user_id = models.UUIDField()
    target_id = models.UUIDField()
    created_at = models.DateTimeField()
    deleted_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "follow"


class Report(models.Model):
    report_id = models.BigAutoField(primary_key=True)
    user_id = models.UUIDField()
    reported_user_id = models.UUIDField()
    report_reason = models.CharField(max_length=255)
    status = models.IntegerField()
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    deleted_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "report"


class UserTagPool(models.Model):
    user_tag_pool_id = models.BigAutoField(primary_key=True)
    user_tag = models.CharField(unique=True, max_length=255, blank=True, null=True)
    created_at = models.DateTimeField()
    deleted_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "user_tag_pool"


class Users(models.Model):
    user_id = models.UUIDField(primary_key=True)
    account_id = models.UUIDField()
    email = models.CharField(max_length=255)
    user_tag = models.CharField(max_length=255)
    username = models.CharField(max_length=255, blank=True, null=True)
    profile_img = models.CharField(max_length=255, blank=True, null=True)
    profile_msg = models.CharField(max_length=255, blank=True, null=True)
    user_tag_changed_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    deleted_at = models.DateTimeField(blank=True, null=True)
    following_cnt = models.IntegerField()
    follower_cnt = models.IntegerField()
    f4f_cnt = models.IntegerField()
    creator_level = models.IntegerField()
    agree_promotion_terms_at = models.DateTimeField(blank=True, null=True)
    app_version = models.CharField(max_length=255, blank=True, null=True)
    device_lang = models.CharField(max_length=255, blank=True, null=True)
    device_type = models.CharField(max_length=255, blank=True, null=True)
    os_type = models.CharField(max_length=255, blank=True, null=True)
    os_version = models.CharField(max_length=255, blank=True, null=True)
    player_id = models.CharField(max_length=255, blank=True, null=True)
    push_token = models.CharField(max_length=255, blank=True, null=True)
    udid = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "users"


# pelican
class Arbecon(models.Model):
    resource_id = models.CharField(max_length=255)
    content = models.OneToOneField("Content", models.DO_NOTHING, primary_key=True)

    class Meta:
        managed = False
        db_table = "arbecon"


class Content(models.Model):
    content_type = models.CharField(max_length=31)
    content_id = models.CharField(primary_key=True, max_length=36)
    created_at = models.DateTimeField(blank=True, null=True)

templates/aurora/pages/operation/new-mg-id-detail.html
{% extends 'aurora/elements/layouts/admin.html' %}
{% load static %}
{% load custom_filters %}
{% block additional_css %}{% endblock %}
{% block content %}

  <style>
    td a:hover {
      color: white;
      /* 마우스 오버시 텍스트 색상을 빨간색으로 변경 */
      background-color: #ed0b4c;
      /* 마우스 오버시 배경색 변경 */
      /* 기타 스타일 변경 가능 */
    }
  </style>
  <div class="page-titles">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="/index">Home</a>
      </li>
      <li class="breadcrumb-item">
        <a href="javascript:void(0)">Operation</a>
      </li>
      <li class="breadcrumb-item active">
        <a href="{% url 'operation:new-mg-id' %}">new mg_id</a>
      </li>
    </ol>
  </div>

  <!-- row -->

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <!-- 선택이미지 -->
          <div class="row">
            <div class="col-lg-12 col-xl-12 col-xxl-12">
              <div class="card">
                <div class="card-body">
                  <div class="row m-b-30">
                    <div class="col-md-5 col-xxl-5">
                      <div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
                        <div class="new-arrivals-img-contnent">
                          {% if crop_img %}
                            <img class="img-fluid" src="data:image/png;base64,{{ crop_img }}" alt="" />
                          {% else %}
                            <img class="img-fluid" src="{{ scanIdToImgUrlDict|get_value_from_dict:scan_id }}" alt=""/>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                    <div class="col-md-7 col-xxl-7">
                      <div class="new-arrival-content position-relative">
                        <ul class="list-group list-group-flush">
                          <li class="list-group-item d-flex px-0 justify-content-between">
                            <strong>scan_id</strong>
                            <a href="{% url 'operation:object-list-scan-id-detail' scan_id=scan_id %}">
                              <span class="mb-0" style="font-size: 14px">{{ scan_id }}</span>
                            </a>                            
                          </li>
                          <li class="list-group-item d-flex px-0 justify-content-between">
                            <strong>user_id</strong>
                            <a href="{% url 'operation:object-list-user-id-detail' user_id=query_data.userId %}">
                              <span class="mb-0" style="font-size: 14px;">
                                {% if matching_user_id_dict|get_value_from_dict:query_data.userId %}
                                  {{ matching_user_id_dict|get_value_from_dict:query_data.userId }}
                                {% else %}
                                  {{ query_data.userId }}
                                {% endif %}
                              </span>
                            </a>                        
                          </li>
                          <li class="list-group-item d-flex px-0 justify-content-between">
                            <strong>timestamp</strong>
                            <span class="mb-0" style="font-size: 14px">{{ query_data.timestamp| date:"y-m-d H:i:s" }}</span>
                          </li>
                          <li class="list-group-item d-flex px-0 justify-content-between">
                            <strong>mg_id</strong>
                            <a href="{% url 'operation:object-list-mg-id-detail' mg_id=query_data.mgId %}">
                              <span class="mb-0" style="font-size: 12px;">{{ query_data.mgId }}</span>
                            </a>                              
                          </li>
                          <li class="list-group-item d-flex px-0 justify-content-between">
                            <strong>geohash</strong>
                            <span class="mb-0" style="font-size: 14px">{{ query_data.gps }}</span>
                          </li>    
                          <li class="list-group-item d-flex px-0 justify-content-between">
                            <strong>shire</strong>
                            <span class="mb-0" style="font-size: 14px">{{ query_data.shire }}</span>
                          </li>                                                                                                                               
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- 후보 -->  
          <div class="row">
            <div class="dropdown custom-dropdown">
              <button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="dropdown" aria-expanded="false">DATA Size:
                {{data_size}}
                <i class="fa fa-angle-down ms-3"></i>
              </button>
              <div class="dropdown-menu dropdown-menu-end" style="">
                <a class="dropdown-item" href="?data_size=20">20</a>
                <a class="dropdown-item" href="?data_size=50">50</a>
                <a class="dropdown-item" href="?data_size=100">100</a>
                <a class="dropdown-item" href="?data_size=300">300</a>
                <a class="dropdown-item" href="?data_size=500">500</a>
              </div>
            </div>            
            <div class="table-responsive">
              <table id="example2-woody" class="display min-w850">
                <thead>
                  <tr>
                    <th>
                      <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="form-check-input" id="checkAll" required=""/>
                        <label class="custom-control-label" for="checkAll"></label>
                      </div>
                    </th>
                    <th>이미지</th>
                    <th>score</th>
                    <th>user_id</th>
                    <th>timestamp</th>
                    <th>shire</th>
                    <th>scan id</th>
                    <th>mg id</th>
                  </tr>
                </thead>
                <tbody>
                  {% for i in search_result %}
                    <tr data-mg-id={{ i.mgId }}>
                      <td>
                        <div class="custom-control custom-checkbox">
                          <input type="checkbox" class="form-check-input" id="customCheckBox2" required=""/>
                          <label class="custom-control-label" for="customCheckBox2"></label>
                        </div>
                      </td>
                      <td>
                        <a href="{% url 'operation:new-mg-id-detail' scan_id=i.scan_id %}">
                          {% if scanIdToImgUrlDict|get_value_from_dict:i.scan_id %}
                            <img class="img-fluid" src="{{ scanIdToImgUrlDict|get_value_from_dict:i.scan_id }}" alt=""  width="120" height="auto"/>
                          {% else %}
                            <img src={% static 'aurora/images/logo.png' %} alt="Image" width="120" height="auto"/>
                          {% endif %}
                        </a>
                      </td>
                      <td>
                        {{ i.score }}
                      </td>
                      <td>
                        <a href="{% url 'operation:object-list-user-id-detail' user_id=i.userId %}">
                          {% if i.userId == query_data.userId%}
                            <span class="mb-0" style="font-size: 14px; background-color: red;">
                          {% else %}
                            <span class="mb-0" style="font-size: 14px;">
                          {% endif %}
                            {% if matching_user_id_dict|get_value_from_dict:i.userId %}
                              {{ matching_user_id_dict|get_value_from_dict:i.userId }}
                            {% else %}
                              {{ i.userId }}
                            {% endif %}
                          </span>
                        </a>   
                      </td>
                      <td>{{ i.timestamp| date:"y-m-d H:i:s" }}</td>
                      <td>{{ i.shire }}</td>
                      <td>
                        <a href="{% url 'operation:object-list-scan-id-detail' scan_id=i.scan_id %}">
                          <span class="mb-0" style="font-size: 10px;">{{ i.scan_id }}</span>
                        </a>
                      </td>
                      <td>            
                        <a href="{% url 'operation:object-list-mg-id-detail' mg_id=i.mgId %}">
                            <span col-name="mg_id", class="mb-0" style="font-size: 12px;">{{ i.mgId }}</span>
                        </a> 
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                      <th>
                        <div class="custom-control custom-checkbox">
                          <input type="checkbox" class="form-check-input" id="checkAll" required=""/>
                          <label class="custom-control-label" for="checkAll"></label>
                        </div>
                      </th>
                      <th>이미지</th>
                      <th>score</th>
                      <th>user_id</th>
                      <th>timestamp</th>
                      <th>shire</th>
                      <th>scan id</th>
                      <th>mg id</th>
                    </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const table = document.querySelector("#example2-woody");
      const rows = Array.from(table.querySelectorAll("tbody tr[data-mg-id]"));
      
      const colors = [
        "red", "green", "blue", "yellow", "orange", "pink", "purple",
        "brown", "gray", "silver", "gold", "cyan", "magenta", "indigo", "violet", "aqua",
        "teal", "lavender", "maroon", "olive", "beige", "turquoise", "coral", "salmon",
        "plum", "slate", "orchid", "ruby", "pearl", "ebony", "ivory", "tangerine", "lemon",
        "mint", "lime", "peach", "charcoal", "mauve", "sepia", "burgundy", "amethyst",
        "periwinkle", "lilac", "celadon", "emerald", "chartreuse", "azure", "aquamarine",
        "cobalt", "sapphire", "garnet", "amber", "topaz", "bronze", "sienna", "terracotta",
        "sand", "khaki", "forest", "moss", "pine", "fern", "caramel", "cinnamon", "chestnut",
        "espresso", "walnut", "cognac", "taupe", "papaya", "blush", "rose", "fuchsia",
        "hotpink", "thistle", "wisteria", "grape", "eggplant", "olivedrab", "peru",
        "rosybrown", "slategray", "dodgerblue", "goldenrod", "tomato", "darkcyan",
        "mediumvioletred", "firebrick", "darkslategray", "mediumorchid", "royalblue",
        "darkorange", "darkseagreen", "cadetblue", "purple", "pink", "lightcoral"
      ];
      
      let colorIndex = 0;
      
      const mgIdColorMap = new Map();
      
      rows.forEach((row) => {
        const mgId = row.getAttribute("data-mg-id");
        
        if (!mgIdColorMap.has(mgId)) {
          mgIdColorMap.set(mgId, colors[colorIndex]);
          colorIndex = (colorIndex + 1) % colors.length;
        }
        
        const colNameElement = row.querySelector('[col-name="mg_id"]');
        colNameElement.style.backgroundColor = mgIdColorMap.get(mgId);
      });
    });
  </script>
{% endblock %}
{% block additional_js %}{% endblock %}