aurora/urls.py
from django.urls import path
from aurora import aurora_views
from users import users_views

app_name = "aurora"

urlpatterns = [
    path("", aurora_views.index, name="index"),
    path("index/", aurora_views.index, name="index"),
    path("page-login/", aurora_views.page_login, name="page-login"),
    path("page-register/", aurora_views.page_register, name="page-register"),
    path(
        "page-forgot-password/",
        aurora_views.page_forgot_password,
        name="page-forgot-password",
    ),
    path("page-lock-screen/", aurora_views.page_lock_screen, name="page-lock-screen"),
    path("page-error-400/", aurora_views.page_error_400, name="page-error-400"),
    path("page-error-403/", aurora_views.page_error_403, name="page-error-403"),
    path("page-error-404/", aurora_views.page_error_404, name="page-error-404"),
    path("page-error-500/", aurora_views.page_error_500, name="page-error-500"),
    path("page-error-503/", aurora_views.page_error_503, name="page-error-503"),
    path("", aurora_views.index, name="index"),
    path("index/", aurora_views.index, name="index"),
    path("login/", users_views.login_user, name="login"),
    path("logout/", users_views.logout_user, name="logout"),
    path("signup/", users_views.signup, name="signup"),
    path("activate/<uidb64>/<token>/", users_views.activate, name="activate"),
    path("users/", users_views.users, name="users"),
    path("user-details/<int:id>/", users_views.user_details, name="user-details"),
    path("add-user/", users_views.add_user, name="add-user"),
    path("edit-user/<int:id>/", users_views.edit_user, name="edit-user"),
    path("delete-user/<int:id>/", users_views.delete_user, name="delete-user"),
    path("permissions/", users_views.permissions, name="permissions"),
    path(
        "edit-permissions/<int:id>/",
        users_views.edit_permissions,
        name="edit-permissions",
    ),
    path(
        "delete-permissions/<int:id>/",
        users_views.delete_permissions,
        name="delete-permissions",
    ),
    path(
        "assign-permissions-to-user/<int:id>/",
        users_views.assign_permissions_to_user,
        name="assign-permissions-to-user",
    ),
]

dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [

    path('', include('aurora.urls', namespace='aurora')),

    path('admin/', admin.site.urls),
    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('change-password/',
    #     auth_views.PasswordChangeView.as_view(template_name='zenix/change-password.html',
    #                                           success_url='/users/'),
    #     name='change-password'
    # ),
    path('password/', users_views.change_password, name='change_password'),

    # data
    path('data/', include('data.urls', namespace='data')),

    # operation
    path("operation/", include('operation.urls', namespace='operation')),

    # administrator
    path("administrator/", include('users.urls', namespace='administrator')),
]

if settings.DEBUG == True or settings.DEBUG == False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"


'''
1- Submit email form                           PasswordResetView.as_view()
2- Email sent success Message                  PasswordResetDoneView.as_view()
3- Link to password Rest form in email         PasswordResetConfirmView.as_view()
4- Password successfully changed message       PasswordResetCompleteView.as_view()

'''

data/urls.py
from data import data_views
from django.urls import path

app_name = 'data'

urlpatterns = [
    path("svc-user-status-daily/", data_views.svc_user_status_daily, name="svc-user-status-daily"),
    path("svc-user-status-month/", data_views.svc_user_status_month, name="svc-user-status-month"),
    path("svc-activity-user/", data_views.svc_activity_user, name="svc-activity-user"),
    path("scan-status-daily/", data_views.scan_status_daily, name="scan-status-daily"),
    path("scan-status-month/", data_views.scan_status_month, name="scan-status-month"),
    path("scan-activity-status/", data_views.scan_activity_status, name="scan-activity-status"),
    path('download-summary-as-csv-user-daily/', data_views.download_summary_as_csv_user_daily, name='download-summary-as-csv-user-daily'),
    path('download-summary-as-csv-user-month/', data_views.download_summary_as_csv_user_month, name='download-summary-as-csv-user-month'),
    path('download-summary-as-csv-active-user/', data_views.download_summary_as_csv_active_user, name='download-summary-as-csv-active-user'),
    path('download-summary-as-csv-scan-daily/', data_views.download_summary_as_csv_scan_daily, name='download-summary-as-csv-scan-daily'),
    path('download-summary-as-csv-scan-month/', data_views.download_summary_as_csv_scan_month, name='download-summary-as-csv-scan-month'),
    path('download-summary-as-csv-active-scan/', data_views.download_summary_as_csv_active_scan, name='download-summary-as-csv-active-scan'),
    #path("scan-status/", data_views.scan_status, name="scan-status"),
]

users/urls.py
from users import users_views
from django.urls import path, re_path

app_name = "users"

urlpatterns = [

    # Roles(Groups)
    path("authority/roles/", users_views.role_list, name="roles"),
    path("authority/roles/<int:id>", users_views.role_user_list, name="role-users"),

    path("authority/roles/role/add", users_views.role_add, name="role-add"),
    path("authority/roles/role/edit/<int:id>", users_views.role_edit, name="role-edit"),
    path("authority/roles/role/delete/<int:id>", users_views.role_delete, name="role-delete"),

    # Permissions
    path("authority/permission/", users_views.permission_list, name="permission-list"),

]

users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


class GroupExpended(models.Model):
    group = models.OneToOneField(Group, on_delete=models.CASCADE, primary_key=True)
    description = models.CharField(max_length=255, null=True, blank=True)

class CustomAccountManager(BaseUserManager):
    def create_superuser(self, email, first_name, last_name, password, **other_fields):
        other_fields.setdefault("is_staff", True)
        other_fields.setdefault("is_superuser", True)
        other_fields.setdefault("is_active", True)

        if other_fields.get("is_staff") is not True:
            raise ValueError("Superuser must be assigned to is_staff=True.")
        if other_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must be assigned to is_superuser=True.")

        super_user = self.create_user(
            email, first_name, last_name, password, **other_fields
        )

        return super_user

    def create_user(self, email, first_name, last_name, password, **other_fields):
        # email validation
        if not email:
            raise ValueError(_("You must provide an email address"))

        email = self.normalize_email(email)
        user = self.model(
            email=email, first_name=first_name, last_name=last_name, **other_fields
        )
        user.set_password(password)
        user.save()
        return user


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f"{instance.email}/{filename}"


# This is the new custom user model
class NewUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    groups = models.ManyToManyField(Group, blank=True)
    about = models.TextField(_("about"), max_length=500, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)  # this false work on ui not in admin
    division = models.CharField(max_length=150, blank=True)  # 조직
    created_at = models.DateTimeField(auto_now_add=True, null=True)  # 생성일
    # when user is created, than system send a email after varify the user we check the user is active

    objects = CustomAccountManager()

    USERNAME_FIELD = (
        "email"  # It's replace the username to email when you login in admin
    )
    REQUIRED_FIELDS = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

users/forms.py
from django import forms
from users.models import NewUser, GroupExpended
from django.contrib.auth.models import Group, Permission
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm


class SignupForm(forms.ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation", widget=forms.PasswordInput
    )
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = NewUser
        fields = (
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
            "division",
        )

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


# Add User Form
class NewUserForm(forms.ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation", widget=forms.PasswordInput
    )
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = NewUser
        fields = (
            "email",
            "first_name",
            "last_name",
            "groups",
            "about",
            "is_active",
            "password1",
            "password2",
        )

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(), required=False
    )

    class Meta:
        model = NewUser
        fields = (
            "email",
            "first_name",
            "last_name",
            "groups",
            "about",
            "is_active",
            "division",
        )

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save()
        return user


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = authenticate(email=email, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError(
                "Sorry, that login was invalid. Please try again."
            )
        return self.cleaned_data

    def login(self, request):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = authenticate(email=email, password=password)
        return user


class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data["email"]
        if not NewUser.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError(
                "There is no user registered with the specified email address!"
            )
        return email


class RoleForm(forms.ModelForm):
    name = forms.CharField(label="Name", help_text="Example: action_modelname")
    description = forms.CharField(label="Description", help_text="Example: action_modelname")
    permissions = forms.ModelMultipleChoiceField(label="Permissions", queryset=Permission.objects.all(), required=False)

    class Meta:
        model = GroupExpended
        fields = '__all__'

class PermissionsForm(forms.ModelForm):
    name = forms.CharField(label="Name", help_text="Example: Can action modelname")
    codename = forms.CharField(label="Code Name", help_text="Example: action_modelname")

    class Meta:
        model = Permission
        fields = ("name", "codename", "content_type")


class UserPermissionsForm(forms.ModelForm):
    class Meta:
        model = NewUser
        fields = ("user_permissions",)

templates/aurora/modules/group-add.html
{% extends 'aurora/elements/layouts/admin.html' %}
{% load static widget_tweaks %}


{% block additional_css %}

{% endblock %}



{% block message %}
{% include 'aurora/elements/alert.html' %}
{% endblock %}


{% block content %}

       <div class="col-lg-12">
          <div class="card">
             <div class="card-header">
                <h4 class="card-title">Add New Group </h4>
             </div>
             <div class="card-body">
                <div id="message">
                </div>
                <form id="user_perm"  method="post">
                   {% csrf_token %}
                   <div class="row">
                      <div class="mb-3 col-md-12">
                         <label class="form-label">Name</label>
                         {{ form.name|attr:"type:text"|attr:"class:form-control"|attr:"placeholder:Name" }}
                      </div>
                      <div class="mb-3 col-md-12">
                         {{ form.permissions|attr:"style:height:300px" }}
                      </div>
                   </div>
                   <button type="submit" class="btn btn-primary mt-5">Save</button>
                   <a href="{% url 'aurora:groups' %}" class="btn btn-primary mt-5"> Back</a>
                </form>
             </div>
          </div>
       </div>


{% endblock %}


{% block additional_js %}
<script type="text/javascript">
    var demo1 = $('select[name=permissions]').bootstrapDualListbox(

        {
            preserveSelectionOnMove: 'moved',
            moveOnSelect: true,
            moveAllLabel: 'Move all',
            moveSelectedLabel: 'Move selected'
        }
    );
    
   
</script>
{% endblock %}



templates/aurora/modules/permissions.html
{% extends 'aurora/elements/layouts/admin.html' %}
{% load static widget_tweaks %}
{% block additional_css %}
{% endblock %}
{% block message %}
{% include 'aurora/elements/alert.html' %}
{% endblock %}
{% block content %}

        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Permissions</h4>
                    {% comment %} {% if perms.auth.add_permission %}
                    <span class="badge badge-primary"><a class="text-light" href="{% url 'aurora:add-permissions' %}">ADD PERMISSIONS &nbsp;<i class="fa fa-plus" aria-hidden="true"></i></a></span>
                    {% endif %} {% endcomment %}
                </div>
                <div class="card-body">
                    <div class="table-responsive ">
                        <table class="table table-responsive-md ck-table">
                            <thead>
                                <tr>
                                    <th style="width:50px;">
                                        <div class="custom-control custom-checkbox checkbox-primary">
                                            <input type="checkbox" class="form-check-input" id="checkAll" required="">
                                            <label class="custom-control-label" for="checkAll"></label>
                                        </div>
                                    </th>

                                    <th scope="col">Name</th>
                                    <th scope="col">Code Name</th>
                                    <th scope="col">Content Type</th>
                                    {% if perms.auth.change_permission or perms.auth.delete_permission %}
                                    <th scope="col">Action</th>
                                    {% endif %}
                                </tr>
                            </thead>
                            <tbody>
                                {% for per in permissions_obj %}
                                <tr >
                                    <td>
                                        <div class="custom-control custom-checkbox checkbox-primary">
                                            <input type="checkbox" class="form-check-input" id="customCheckBox2" required="">
                                            <label class="custom-control-label" for="customCheckBox2"></label>
                                        </div>
                                    </td>

                                    <td>{{ per.name }}</td>
                                    <td><span class="badge  badge-xs badge-primary">{{ per.codename }}</div></td>
                                    <td>{{ per.content_type }}</td>
                                    </td>
                                    {% if perms.auth.change_permission or perms.auth.delete_permission %}
                                    <td>
                                        <span class="sweetalert">
                                            {% if perms.auth.change_permission %}
                                            <a href="{% url 'aurora:edit-permissions' id=per.id %}" class="btn btn-primary shadow btn-xs sharp me-2" data-bs-toggle="tooltip" data-placement="top" title="Edit"><i class="fas fa-pencil-alt color-muted"></i> </a>
                                            {% endif %}
                                            {% if perms.auth.delete_permission %}
                                            <a href="{% url 'aurora:delete-permissions' id=per.id %}" class="sweet-success-cancel btn btn-danger shadow btn-xs sharp me-2" data-bs-toggle="tooltip" data-placement="top" title="Close"><i class="fa fa-trash"></i></a>
                                            {% endif %}
                                        </span>
                                    </td>
                                    {% endif %}
                                </tr>
                                {% endfor %}
                            </tbody>

                        </table>

                        <nav mt-5>

                            <p>
                                <span class="current">
                                Page {{ permissions_obj.number }} of {{ permissions_obj.paginator.num_pages }}.
                               </span> 
                               </p>
                               

                            <ul class="pagination pagination-gutter  justify-content-end">
                                
                                    <li class="page-item page-indicator ">
                                        <a class="page-link" href="{% if permissions_obj.has_previous %}
                                                                    ?page={{ permissions_obj.previous_page_number }}
                                                                    {% else %}
                                                                    javascript:void(0);
                                                                    {% endif %}">
                                            <i class="la la-angle-left"></i></a>
                                    </li>
    
                                {% for i in permissions_obj.paginator.page_range|slice:":3" %}
    
                                    <li class="page-item {% if permissions_obj.number == i %}
                                                        active{% endif %}"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                
                                {% endfor %}
    
                                
                                {% if permissions_obj.number > 3 %}
                                <li class="page-item active"><a class="page-link" href="?page={{ permissions_obj.number }}">{{ permissions_obj.number }}</a></li>
                                {% endif %}
                                
                                <li class="page-item page-indicator ">
                                    <a class="page-link"  href="{% if permissions_obj.has_next %}
                                                                ?page={{ permissions_obj.next_page_number }}
                                                                {% else %}
                                                                javascript:void(0);
                                                                {% endif %}">
                                        <i class="la la-angle-right"></i></a>
                                </li>
                                <li>
                                </li>
                            </ul>
                           
                    </nav>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}


{% block additional_js %}
<script>
    $('.sweet-success-cancel').on('click', function (event) {
           event.preventDefault();
           const url = $(this).attr('href');
   
           Swal.fire({
               title: 'Are you sure?',
               text: "You won't be able to revert this!",
               type: "warning",
               icon: 'question',
               showCancelButton: true,
               confirmButtonText: "Yes, delete it !!",
               confirmButtonText: 'Delete',
               confirmButtonColor: "#DD6B55"
               
           }).then((result) => {
               if (result.value) {
                   window.location.href = url;
               } else if (result.dismiss === Swal.DismissReason.cancel) {
                   event.preventDefault();
               }
           })
       });
   </script>
{% endblock %}



templates/aurora/modules/users.html
{% extends 'aurora/elements/layouts/admin.html' %}
{% load static %}
{% block additional_css %}{% endblock %}
{% block message %}
  {% include 'aurora/elements/alert.html' %}
{% endblock %}
{% block content %}

  <div class="card">
    <div class="card-header d-sm-flex d-block">
      <div class="me-auto mb-sm-0 mb-3">
        <h4 class="card-title mb-2">User Listing</h4>
        <p class="mb-2">Total user :
          {{ total_user_count }}</p>
        <span></span>
      </div>
      {% if perms.users.add_newuser %}
        <a href="{% url 'aurora:add-user' %}" class="btn btn-primary">+ Add User</a>
      {% endif %}
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table id="example" class="display min-w850">
          <thead>
            <tr>
              <th>#</th>
              <th>User</th>
              <th>생성일</th>
              <th>마지막접속일</th>
              <th>조직</th>
              <th>Groups</th>
              <th>Status</th>
              {% if perms.users.delete_newuser or perms.users.change_newuser or perms.auth.change_permission %}
                <th>Action</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for user in user_list %}
              <tr>
                <td>
                  <h6>{{ forloop.counter }}</h6>
                </td>
                <td>
                  <div class="media style-1">
                    <div class="media-body">
                      <a href="{% url 'aurora:user-details' id=user.id %}">
                        <h6>{{ user.first_name }}
                          {{ user.last_name }}</h6>
                        <span>{{ user.email }}</span>
                      </a>
                    </div>
                  </div>
                </td>
                <td>{{ user.created_at | date:"y-m-d H:i:s" }}</td>
                <td>{{ user.last_login | date:"y-m-d H:i:s" }}</td>
                <td>{{ user.division }}</td>
                <td>
                  <div>
                    {% for g in user.groups.all %}
                      <span class="badge badge-xs badge-primary">{{ g.name }}</span>
                    {% endfor %}
                  </div>
                </td>
                <td>
                  {% if user.is_active %}
                    <i class="fa fa-user text-success" aria-hidden="true"></i>
                  {% else %}
                    <i class="fa fa-user text-dark" aria-hidden="true"></i>
                  {% endif %}

                  {% if user.is_superuser %}
                    <i class="fa fa-user-secret text-success" aria-hidden="true"></i>
                  {% else %}
                    <i class="fa fa-user-secret text-dark" aria-hidden="true"></i>
                  {% endif %}
                </td>
                <td>
                  <div class="d-flex action-button">
                    {% if perms.auth.change_permission %}
                      <a href="{% url 'aurora:assign-permissions-to-user' id=user.id %}" class="btn btn-info btn-xs px-2">
                        <svg id="Capa_1" enable-background="new 0 0 512 512" height="20" viewbox="0 0 512 512" width="20" xmlns="http://www.w3.org/2000/svg">
                          <g>
                            <path d="m459.669 82.906-196-81.377c-4.91-2.038-10.429-2.039-15.338 0l-196 81.377c-7.465 3.1-12.331 10.388-12.331 18.471v98.925c0 136.213 82.329 258.74 208.442 310.215 4.844 1.977 10.271 1.977 15.116 0 126.111-51.474 208.442-174.001 208.442-310.215v-98.925c0-8.083-4.865-15.371-12.331-18.471zm-27.669 117.396c0 115.795-68 222.392-176 269.974-105.114-46.311-176-151.041-176-269.974v-85.573l176-73.074 176 73.074zm-198.106 67.414 85.964-85.963c7.81-7.81 20.473-7.811 28.284 0s7.81 20.474-.001 28.284l-100.105 100.105c-7.812 7.812-20.475 7.809-28.284 0l-55.894-55.894c-7.811-7.811-7.811-20.474 0-28.284s20.474-7.811 28.284 0z"/>
                          </g>
                        </svg>
                      </a>
                    {% endif %}
                    {% if perms.users.change_newuser %}
                      <a href="{% url 'aurora:edit-user' id=user.id %}" class="btn btn-info btn-xs px-2 mx-2">
                        <svg width="20" height="20" viewbox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M17 3C17.2626 2.73735 17.5744 2.52901 17.9176 2.38687C18.2608 2.24473 18.6286 2.17157 19 2.17157C19.3714 2.17157 19.7392 2.24473 20.0824 2.38687C20.4256 2.52901 20.7374 2.73735 21 3C21.2626 3.26264 21.471 3.57444 21.6131 3.9176C21.7553 4.26077 21.8284 4.62856 21.8284 5C21.8284 5.37143 21.7553 5.73923 21.6131 6.08239C21.471 6.42555 21.2626 6.73735 21 7L7.5 20.5L2 22L3.5 16.5L17 3Z" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                        </svg>
                      </a>
                    {% endif %}
                    {% if perms.users.delete_newuser %}
                      <div class="sweetalert">
                        <a href="{% url 'aurora:delete-user' id=user.id %}" class="btn btn-xs px-2 btn-danger sweet-success-cancel">
                          <svg width="20" height="20" viewbox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M3 6H5H21" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path d="M8 6V4C8 3.46957 8.21071 2.96086 8.58579 2.58579C8.96086 2.21071 9.46957 2 10 2H14C14.5304 2 15.0391 2.21071 15.4142 2.58579C15.7893 2.96086 16 3.46957 16 4V6M19 6V20C19 20.5304 18.7893 21.0391 18.4142 21.4142C18.0391 21.7893 17.5304 22 17 22H7C6.46957 22 5.96086 21.7893 5.58579 21.4142C5.21071 21.0391 5 20.5304 5 20V6H19Z" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                          </svg>
                        </a>
                      </div>
                    {% endif %}
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock %}
{% block additional_js %}

  <script>
    $(".sweet-success-cancel").on("click", function (event) {
      event.preventDefault();
      const url = $(this).attr("href");

      Swal
        .fire({
          title: "Are you sure?",
          text: "You won't be able to revert this!",
          type: "warning",
          icon: "question",
          showCancelButton: true,
          confirmButtonText: "Yes, delete it !!",
          confirmButtonText: "Delete",
          confirmButtonColor: "#DD6B55"
        })
        .then((result) => {
          if (result.value) {
            window.location.href = url;
          } else if (result.dismiss === Swal.DismissReason.cancel) {
            event.preventDefault();
          }
        });
    });
  </script>

{% endblock %}