dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [

    path('', include('aurora.urls', namespace='aurora')),

    path('admin/', admin.site.urls),
    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('change-password/',
    #     auth_views.PasswordChangeView.as_view(template_name='zenix/change-password.html',
    #                                           success_url='/users/'),
    #     name='change-password'
    # ),
    path('password/', users_views.change_password, name='change_password'),

    # data
    path('data/', include('data.urls', namespace='data')),

    # operation
    path("operation/", include('operation.urls', namespace='operation')),

    # administrator
    path("administrator/", include('users.urls', namespace='administrator')),
]

if settings.DEBUG == True or settings.DEBUG == False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"


'''
1- Submit email form                           PasswordResetView.as_view()
2- Email sent success Message                  PasswordResetDoneView.as_view()
3- Link to password Rest form in email         PasswordResetConfirmView.as_view()
4- Password successfully changed message       PasswordResetCompleteView.as_view()

'''

data/urls.py
from data import data_views
from django.urls import path

app_name = 'data'

urlpatterns = [
    path("svc-user-status-daily/", data_views.svc_user_status_daily, name="svc-user-status-daily"),
    path("svc-user-status-month/", data_views.svc_user_status_month, name="svc-user-status-month"),
    path("svc-activity-user/", data_views.svc_activity_user, name="svc-activity-user"),
    path("scan-status-daily/", data_views.scan_status_daily, name="scan-status-daily"),
    path("scan-status-month/", data_views.scan_status_month, name="scan-status-month"),
    path("scan-activity-status/", data_views.scan_activity_status, name="scan-activity-status"),
    path('download-summary-as-csv-user-daily/', data_views.download_summary_as_csv_user_daily, name='download-summary-as-csv-user-daily'),
    path('download-summary-as-csv-user-month/', data_views.download_summary_as_csv_user_month, name='download-summary-as-csv-user-month'),
    path('download-summary-as-csv-active-user/', data_views.download_summary_as_csv_active_user, name='download-summary-as-csv-active-user'),
    path('download-summary-as-csv-scan-daily/', data_views.download_summary_as_csv_scan_daily, name='download-summary-as-csv-scan-daily'),
    path('download-summary-as-csv-scan-month/', data_views.download_summary_as_csv_scan_month, name='download-summary-as-csv-scan-month'),
    path('download-summary-as-csv-active-scan/', data_views.download_summary_as_csv_active_scan, name='download-summary-as-csv-active-scan'),
    #path("scan-status/", data_views.scan_status, name="scan-status"),
]

templates/aurora/pages/data/scan-activity-status.html
{% extends 'aurora/elements/layouts/admin.html' %}

{% load static %}
{% load mathfilters %}

{% block additional_css %}
{% endblock %}

{% block content %}

{% include "aurora/pages/data/scan-status-tab.html" %}


<div class="col-xl-12">
    <div class="d-sm-flex  d-block align-items-center mb-4">
        <div class="me-auto">
            <h4 class="fs-20 text-black" style="margin-top: 10px;">스캔 현황(시간별)</h4>
            <span class="fs-12">Arbeon 시간별 스캔 현황</span>
        </div>
        
        <a href="/data/download-summary-as-csv-active-scan" class="btn btn-primary">시간별 스캔 현황 다운로드</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive table-hover fs-14">
            <table class="table display mb-4 dataTablesCard " id="example5">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th colspan="2">스캔</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th colspan="2">스캔비율</th>
                        <th colspan="2">평균 스캔 회원 수</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <th>날짜</th>
                        <th>시간</th>
                        <th>성공</th>
                        <th>실패</th>
                        <th>합계</th>
                        <th>스캔 참여 회원</th>
                        <th>인당 스캔 수</th>
                        <th>성공</th>
                        <th>실패</th>
                        <th>성공</th>
                        <th>실패</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in all_data %}
                    <tr>
                        <td><span class="text-black font-w500">{{ data.summary_dt }}</span></td>
                        <td><span class="text-black font-w500">{{ data.summary_hour }}</span></td>
                        <td><span class="text-black font-w500">{{ data.scan_success }}</span></td>
                        <td><span class="text-black font-w500">{{ data.scan_fail }}</span></td>
                        <td><span class="text-black font-w500">{{ data.scan_success|add:data.scan_fail }}</span></td>

                        <td><span class="text-black font-w500">{{ data.total_scan_user }}</span></td>
                        <td>
                            {% if data.total_scan_user > 0 %}
                            <span class="text-black font-w500">
                                {{ data.scan_success|add:data.scan_fail|div:data.total_scan_user|floatformat:"2" }}
                            </span>
                            {% else %}
                            <span class="text-black font-w500">0</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.scan_success|add:data.scan_fail > 0 %}
                            {% with numerator=data.scan_success|add:data.scan_fail%}
                            <span class="text-black font-w500">
                                {{ data.scan_success|div:numerator|mul:100|floatformat:"2" }}%
                            </span>
                            {% endwith %}
                            {% else %}
                            <span class="text-black font-w500">0%</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.scan_success|add:data.scan_fail > 0 %}
                            {% with numerator=data.scan_success|add:data.scan_fail%}
                            <span class="text-black font-w500">
                                {{ data.scan_fail|div:numerator|mul:100|floatformat:"2" }}%
                            </span>
                            {% endwith %}
                            {% else %}
                            <span class="text-black font-w500">0%</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.total_scan_user > 0 %}
                            <span class="text-black font-w500">
                                {{ data.scan_success|div:data.total_scan_user|floatformat:"2" }}
                            </span>
                            {% else %}
                            <span class="text-black font-w500">0</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.total_scan_user > 0 %}
                            <span class="text-black font-w500">
                                {{ data.scan_fail|div:data.total_scan_user|floatformat:"2" }}
                            </span>
                            {% else %}
                            <span class="text-black font-w500">0</span>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {% if all_data.has_previous %}
            <li class="page-item page-indicator">
              <a class="page-link" href="?page={{ all_data.previous_page_number }}">
                <i class="la la-angle-left"></i>
              </a>
            </li>
            {% endif %} {% for page_num in all_data.paginator.page_range %}
            <li class="page-item{% if page_num == all_data.number %} active{% endif %}">
              <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% endfor %} {% if all_data.has_next %}
            <li class="page-item page-indicator">
              <a class="page-link" href="?page={{ all_data.paginator.num_pages }}">
                <i class="la la-angle-right"></i>
              </a>
            </li>
            {% endif %}
          </ul>
    </div>
</div>

{% endblock %}

{% block additional_js %}
<script>
    (function ($) {
        var table = $('#example5').DataTable({
            searching: false,
            paging: true,
            select: false,
            //info: false,         
            lengthChange: false

        });
        $('#example tbody').on('click', 'tr', function () {
            var data = table.row(this).data();

        });
    })(jQuery);
</script>
{% endblock %}

templates/aurora/pages/data/scan-status-daily.html
{% extends 'aurora/elements/layouts/admin.html' %}

{% load static %}
{% load mathfilters %}

{% block additional_css %}
{% endblock %}

{% block content %}

{% include "aurora/pages/data/scan-status-tab.html" %}

<div class="col-xl-12">
    <div class="d-sm-flex  d-block align-items-center mb-4">
        <div class="me-auto">
            <h4 class="fs-20 text-black" style="margin-top: 10px;">스캔 현황(일별)</h4>
            <span class="fs-12">Arbeon 일별 스캔 현황</span>
        </div>
        
        <a href="/data/download-summary-as-csv-scan-daily" class="btn btn-primary">일별 스캔 현황 다운로드</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive table-hover fs-14">
            <table class="table display mb-4 dataTablesCard " id="example5">
                <thead>
                    <tr>
                        <th></th>
                        <th colspan="2">스캔</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th colspan="2">스캔비율</th>
                        <th colspan="2">평균 스캔 회원 수</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <th>날짜</th>
                        <th>성공</th>
                        <th>실패</th>
                        <th>합계</th>
                        <th>스캔 참여 회원</th>
                        <th>인당 스캔 수</th>
                        <th>성공</th>
                        <th>실패</th>
                        <th>성공</th>
                        <th>실패</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in all_data %}
                    <tr>
                        <td><span class="text-black font-w500">{{ data.summary_dt }}</span></td>
                        <td><span class="text-black font-w500">{{ data.scan_success }}</span></td>
                        <td><span class="text-black font-w500">{{ data.scan_fail }}</span></td>
                        <td><span class="text-black font-w500">{{ data.scan_success|add:data.scan_fail }}</span></td>

                        <td><span class="text-black font-w500">{{ data.total_scan_user }}</span></td>
                        <!--신규회원 기준 dau 산정 필요-->
                        <td>
                            {% if data.total_scan_user > 0 %}
                            <span class="text-black font-w500">
                                {{ data.scan_success|add:data.scan_fail|div:data.total_scan_user|floatformat:"2" }}
                            </span>
                            {% else %}
                            <span class="text-black font-w500">0</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.scan_success|add:data.scan_fail > 0 %}
                            {% with numerator=data.scan_success|add:data.scan_fail%}
                            <span class="text-black font-w500">
                                {{ data.scan_success|div:numerator|mul:100|floatformat:"2" }}%
                            </span>
                            {% endwith %}
                            {% else %}
                            <span class="text-black font-w500">0%</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.scan_success|add:data.scan_fail > 0 %}
                            {% with numerator=data.scan_success|add:data.scan_fail%}
                            <span class="text-black font-w500">
                                {{ data.scan_fail|div:numerator|mul:100|floatformat:"2" }}%
                            </span>
                            {% endwith %}
                            {% else %}
                            <span class="text-black font-w500">0%</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.total_scan_user > 0 %}
                            <span class="text-black font-w500">
                                {{ data.scan_success|div:data.total_scan_user|floatformat:"2" }}
                            </span>
                            {% else %}
                            <span class="text-black font-w500">0</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.total_scan_user > 0 %}
                            <span class="text-black font-w500">
                                {{ data.scan_fail|div:data.total_scan_user|floatformat:"2"}}
                            </span>
                            {% else %}
                            <span class="text-black font-w500">0</span>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {% if all_data.has_previous %}
            <li class="page-item page-indicator">
              <a class="page-link" href="?page={{ all_data.previous_page_number }}">
                <i class="la la-angle-left"></i>
              </a>
            </li>
            {% endif %} {% for page_num in all_data.paginator.page_range %}
            <li class="page-item{% if page_num == all_data.number %} active{% endif %}">
              <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% endfor %} {% if all_data.has_next %}
            <li class="page-item page-indicator">
              <a class="page-link" href="?page={{ all_data.paginator.num_pages }}">
                <i class="la la-angle-right"></i>
              </a>
            </li>
            {% endif %}
          </ul>
    </div>
</div>

{% endblock %}

{% block additional_js %}
<script>
    (function ($) {
        var table = $('#example5').DataTable({
            searching: false,
            paging: true,
            select: false,
            //info: false,         
            lengthChange: false

        });
        $('#example tbody').on('click', 'tr', function () {
            var data = table.row(this).data();

        });
    })(jQuery);
</script>
{% endblock %}

templates/aurora/pages/data/scan-status-month.html
{% extends 'aurora/elements/layouts/admin.html' %}

{% load static %}
{% load mathfilters %}
{% block additional_css %}
{% endblock %}

{% block content %}

{% include "aurora/pages/data/scan-status-tab.html" %}

<div class="col-xl-12">
    <div class="d-sm-flex  d-block align-items-center mb-4">
        <div class="me-auto">
            <h4 class="fs-20 text-black" style="margin-top: 10px;">스캔 현황(월별)</h4>
            <span class="fs-12">Arbeon 월별 스캔 현황</span>
        </div>
        
        <a href="/data/download-summary-as-csv-scan-month" class="btn btn-primary">월별 스캔 현황 다운로드</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive table-hover fs-14">
            <table class="table display mb-4 dataTablesCard " id="example5">
                <thead>
                    <tr>
                        <th></th>
                        <th colspan="2">스캔</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th colspan="2">스캔비율</th>
                        <th colspan="2">평균 스캔 회원 수</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <th>날짜</th>
                        <th>성공</th>
                        <th>실패</th>
                        <th>합계</th>
                        <th>스캔 참여 회원</th>
                        <th>인당 스캔 수</th>
                        <th>성공</th>
                        <th>실패</th>
                        <th>성공</th>
                        <th>실패</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in all_data %}
                    <tr>
                        <td><span class="text-black font-w500">{{ data.summary_dt }}</span></td>
                        <td><span class="text-black font-w500">{{ data.scan_success }}</span></td>
                        <td><span class="text-black font-w500">{{ data.scan_fail }}</span></td>
                        <td><span class="text-black font-w500">{{ data.scan_success|add:data.scan_fail }}</span></td>

                        <td><span class="text-black font-w500">{{ data.total_scan_user }}</span></td>
                        <!--신규회원 기준 dau 산정 필요-->
                        <td>
                            {% if data.total_scan_user > 0 %}
                            <span class="text-black font-w500">
                                {{ data.scan_success|add:data.scan_fail|div:data.total_scan_user|floatformat:"2" }}
                            </span>
                            {% else %}
                            <span class="text-black font-w500">0</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.scan_success|add:data.scan_fail > 0 %}
                            {% with numerator=data.scan_success|add:data.scan_fail%}
                            <span class="text-black font-w500">
                                {{ data.scan_success|div:numerator|mul:100|floatformat:"2" }}%
                            </span>
                            {% endwith %}
                            {% else %}
                            <span class="text-black font-w500">0%</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.scan_success|add:data.scan_fail > 0 %}
                            {% with numerator=data.scan_success|add:data.scan_fail%}
                            <span class="text-black font-w500">
                                {{ data.scan_fail|div:numerator|mul:100|floatformat:"2" }}%
                            </span>
                            {% endwith %}
                            {% else %}
                            <span class="text-black font-w500">0%</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.total_scan_user > 0 %}
                            <span class="text-black font-w500">
                                {{ data.scan_success|div:data.total_scan_user|floatformat:"2" }}
                            </span>
                            {% else %}
                            <span class="text-black font-w500">0</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if data.total_scan_user > 0 %}
                            <span class="text-black font-w500">
                                {{ data.scan_fail|div:data.total_scan_user|floatformat:"2" }}
                            </span>
                            {% else %}
                            <span class="text-black font-w500">0</span>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {% if all_data.has_previous %}
            <li class="page-item page-indicator">
              <a class="page-link" href="?page={{ all_data.previous_page_number }}">
                <i class="la la-angle-left"></i>
              </a>
            </li>
            {% endif %} {% for page_num in all_data.paginator.page_range %}
            <li class="page-item{% if page_num == all_data.number %} active{% endif %}">
              <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% endfor %} {% if all_data.has_next %}
            <li class="page-item page-indicator">
              <a class="page-link" href="?page={{ all_data.paginator.num_pages }}">
                <i class="la la-angle-right"></i>
              </a>
            </li>
            {% endif %}
          </ul>
    </div>
</div>

{% endblock %}

{% block additional_js %}
<script>
    (function ($) {
        var table = $('#example5').DataTable({
            searching: false,
            paging: true,
            select: false,
            //info: false,         
            lengthChange: false

        });
        $('#example tbody').on('click', 'tr', function () {
            var data = table.row(this).data();

        });
    })(jQuery);
</script>
{% endblock %}

templates/aurora/pages/data/scan-status-tab.html
<div class="page-titles">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/index">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:void(0)">Data(지표)</a></li>
        <li class="breadcrumb-item">
            <a href="/data/svc-user-status-daily">스캔 현황</a>
        </li>
        {% if page_title == "스캔 현황(일별)" %}
        <li class="breadcrumb-item active">
            <a href="/data/scan-status-daily">스캔 현황(일별)</a>
        </li>
        {% elif page_title == "스캔 현황(월별)" %}
        <li class="breadcrumb-item active">
            <a href="/data/scan-status-month">스캔 현황(월별)</a>
        </li>
        {% elif page_title == "스캔 현황(시간별)" %}
        <li class="breadcrumb-item active">
            <a href="/data/scan-activity-status">스캔 현황(시간별)</a>
        </li>
        <!--else 예외처리 필요-->
        {% endif %}
    </ol>
</div>
<div class="card-action card-tabs mt-3 mt-sm-0">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link {% if page_title == '스캔 현황(일별)' %}active{% endif %}"
                href="{% url 'data:scan-status-daily'%}">스캔 현황(일별)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if page_title == '스캔 현황(월별)' %}active{% endif %}"
                href="{% url 'data:scan-status-month'%}">스캔 현황(월별)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if page_title == '스캔 현황(시간별)' %}active{% endif %}"
                href="{% url 'data:scan-activity-status'%}">스캔 현황(시간별)</a>
        </li>
    </ul>
</div>

templates/aurora/pages/data/status-base.html
{% extends 'aurora/elements/layouts/admin.html' %}
{% block content %}
{% include "aurora/pages/data/status-tab.html" %}

<div class="tab-content">
    <div class="tab-pane fade show active" id="qwe">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc id ornare libero. Vivamus iaculis, justo vel mattis pharetra, nisi ligula varius nisl, sit amet mollis tortor ligula vitae nisi.</p>
    </div>
    <div class="tab-pane fade" id="asd">
      <p>Nunc vitae turpis id nibh sodales commodo et non augue. Proin fringilla ex nunc. Integer tincidunt risus ut facilisis tristique.</p>
    </div>
    <div class="tab-pane fade" id="zxc">
      <p>Curabitur dignissim quis nunc vitae laoreet. Etiam ut mattis leo, vel fermentum tellus. Sed sagittis rhoncus venenatis. Quisque commodo consectetur faucibus. Aenean eget ultricies justo.</p>
    </div>

{% endblock %}

templates/aurora/pages/data/svc-activity-user.html
{% extends 'aurora/elements/layouts/admin.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}

{% include "aurora/pages/data/svc-user-status-tab.html" %}


<div class="col-xl-12">
    <div class="d-sm-flex  d-block align-items-center mb-4">
        <div class="me-auto">
            <h4 class="fs-20 text-black" style="margin-top: 10px;">기간별 이용자</h4>
            <span class="fs-12">Arbeon 기간별 이용자의 현황</span>
        </div>
        
          <a href="/data/download-summary-as-csv-active-user" class="btn btn-primary">기간별 이용자 현황 다운로드</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive table-hover fs-14">
            <table class="table display mb-4 dataTablesCard " id="example5">
                <thead>
                    <tr>
                        <th>날짜</th>
                        <th>07일 이용자</th>
                        <th>30일 이용자</th>
                        <th>60일 이용자</th>
                        <th>90일 이용자</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in all_data %}
                    <tr>
                        <td><span class="text-black font-w500">{{ data.summary_dt }}</span></td>
                        <td><span class="text-black font-w500">{{ data.use_day_7 }}</span></td>
                        <td><span class="text-black font-w500">{{ data.use_day_30 }}</span></td>
                        <td><span class="text-black font-w500">{{ data.use_day_60 }}</span></td>
                        <td><span class="text-black font-w500">{{ data.use_day_90 }}</span></td><!--신규회원 기준 dau 산정 필요-->
                    
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {% if all_data.has_previous %}
            <li class="page-item page-indicator">
              <a class="page-link" href="?page={{ all_data.previous_page_number }}">
                <i class="la la-angle-left"></i>
              </a>
            </li>
            {% endif %} {% for page_num in all_data.paginator.page_range %}
            <li class="page-item{% if page_num == all_data.number %} active{% endif %}">
              <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% endfor %} {% if all_data.has_next %}
            <li class="page-item page-indicator">
              <a class="page-link" href="?page={{ all_data.paginator.num_pages }}">
                <i class="la la-angle-right"></i>
              </a>
            </li>
            {% endif %}
          </ul>
    </div>
</div>

{% endblock %}

{% block additional_js %}
<script>
    (function ($) {
        var table = $('#example5').DataTable({
            searching: false,
            paging: true,
            select: false,
            //info: false,         
            lengthChange: false

        });
        $('#example tbody').on('click', 'tr', function () {
            var data = table.row(this).data();

        });
    })(jQuery);
</script>
{% endblock %}

templates/aurora/pages/data/svc-user-status-tab.html
<div class="page-titles">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/index">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:void(0)">Data(지표)</a></li>
        <li class="breadcrumb-item">
            <a href="/data/svc-user-status-daily">이용자 현황</a>
        </li>
        {% if page_title == "이용자 현황(일별)" %}
        <li class="breadcrumb-item active">
            <a href="/data/svc-user-status-daily">이용자 현황(일별)</a>
        </li>
        {% elif page_title == "이용자 현황(월별)" %}
        <li class="breadcrumb-item active">
            <a href="/data/svc-user-status-month">이용자 현황(월별)</a>
        </li>
        {% elif page_title == "기간별 이용자" %}
        <li class="breadcrumb-item active">
            <a href="/data/svc-activity-user">기간별 이용자</a>
        </li>
        <!--else 예외처리 필요-->
        {% endif %}
    </ol>
</div>
<div class="card-action card-tabs mt-3 mt-sm-0">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link {% if page_title == '이용자 현황(일별)' %}active{% endif %}"
                href="{% url 'data:svc-user-status-daily'%}">이용자 현황(일별)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if page_title == '이용자 현황(월별)' %}active{% endif %}"
                href="{% url 'data:svc-user-status-month'%}">이용자 현황(월별)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if page_title == '기간별 이용자' %}active{% endif %}"
                href="{% url 'data:svc-activity-user'%}">기간별 이용자</a>
        </li>
    </ul>
</div>