aurora/urls.py
from django.urls import path
from aurora import aurora_views
from users import users_views

app_name = "aurora"

urlpatterns = [
    path("", aurora_views.index, name="index"),
    path("index/", aurora_views.index, name="index"),
    path("page-login/", aurora_views.page_login, name="page-login"),
    path("page-register/", aurora_views.page_register, name="page-register"),
    path(
        "page-forgot-password/",
        aurora_views.page_forgot_password,
        name="page-forgot-password",
    ),
    path("page-lock-screen/", aurora_views.page_lock_screen, name="page-lock-screen"),
    path("page-error-400/", aurora_views.page_error_400, name="page-error-400"),
    path("page-error-403/", aurora_views.page_error_403, name="page-error-403"),
    path("page-error-404/", aurora_views.page_error_404, name="page-error-404"),
    path("page-error-500/", aurora_views.page_error_500, name="page-error-500"),
    path("page-error-503/", aurora_views.page_error_503, name="page-error-503"),
    path("", aurora_views.index, name="index"),
    path("index/", aurora_views.index, name="index"),
    path("login/", users_views.login_user, name="login"),
    path("logout/", users_views.logout_user, name="logout"),
    path("signup/", users_views.signup, name="signup"),
    path("activate/<uidb64>/<token>/", users_views.activate, name="activate"),
    path("users/", users_views.users, name="users"),
    path("user-details/<int:id>/", users_views.user_details, name="user-details"),
    path("add-user/", users_views.add_user, name="add-user"),
    path("edit-user/<int:id>/", users_views.edit_user, name="edit-user"),
    path("delete-user/<int:id>/", users_views.delete_user, name="delete-user"),
    path("permissions/", users_views.permissions, name="permissions"),
    path(
        "edit-permissions/<int:id>/",
        users_views.edit_permissions,
        name="edit-permissions",
    ),
    path(
        "delete-permissions/<int:id>/",
        users_views.delete_permissions,
        name="delete-permissions",
    ),
    path(
        "assign-permissions-to-user/<int:id>/",
        users_views.assign_permissions_to_user,
        name="assign-permissions-to-user",
    ),
]

dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [

    path('', include('aurora.urls', namespace='aurora')),

    path('admin/', admin.site.urls),
    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('change-password/',
    #     auth_views.PasswordChangeView.as_view(template_name='zenix/change-password.html',
    #                                           success_url='/users/'),
    #     name='change-password'
    # ),
    path('password/', users_views.change_password, name='change_password'),

    # data
    path('data/', include('data.urls', namespace='data')),

    # operation
    path("operation/", include('operation.urls', namespace='operation')),

    # administrator
    path("administrator/", include('users.urls', namespace='administrator')),
]

if settings.DEBUG == True or settings.DEBUG == False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"


'''
1- Submit email form                           PasswordResetView.as_view()
2- Email sent success Message                  PasswordResetDoneView.as_view()
3- Link to password Rest form in email         PasswordResetConfirmView.as_view()
4- Password successfully changed message       PasswordResetCompleteView.as_view()

'''

data/urls.py
from data import data_views
from django.urls import path

app_name = 'data'

urlpatterns = [
    path("svc-user-status-daily/", data_views.svc_user_status_daily, name="svc-user-status-daily"),
    path("svc-user-status-month/", data_views.svc_user_status_month, name="svc-user-status-month"),
    path("svc-activity-user/", data_views.svc_activity_user, name="svc-activity-user"),
    path("scan-status-daily/", data_views.scan_status_daily, name="scan-status-daily"),
    path("scan-status-month/", data_views.scan_status_month, name="scan-status-month"),
    path("scan-activity-status/", data_views.scan_activity_status, name="scan-activity-status"),
    path('download-summary-as-csv-user-daily/', data_views.download_summary_as_csv_user_daily, name='download-summary-as-csv-user-daily'),
    path('download-summary-as-csv-user-month/', data_views.download_summary_as_csv_user_month, name='download-summary-as-csv-user-month'),
    path('download-summary-as-csv-active-user/', data_views.download_summary_as_csv_active_user, name='download-summary-as-csv-active-user'),
    path('download-summary-as-csv-scan-daily/', data_views.download_summary_as_csv_scan_daily, name='download-summary-as-csv-scan-daily'),
    path('download-summary-as-csv-scan-month/', data_views.download_summary_as_csv_scan_month, name='download-summary-as-csv-scan-month'),
    path('download-summary-as-csv-active-scan/', data_views.download_summary_as_csv_active_scan, name='download-summary-as-csv-active-scan'),
    #path("scan-status/", data_views.scan_status, name="scan-status"),
]

operation/urls.py
from operation import operation_views
from django.urls import path, re_path

app_name = "operation"

urlpatterns = [
    path("svc-user-list/", operation_views.svc_user_list, name="svc-user-list"),
    path("content-list/", operation_views.content_list, name="content-list"),
    path("report-list/", operation_views.report_list, name="report-list"),
    # 이용자 관리
    path("user-management/", operation_views.user_management, name="user-management"),
    re_path(
        r"^user-management/account-id-detail/(?P<account_id>[\w-]+)/$",
        operation_views.accountid_detail,
        name="user-management-account-id-detail",
    ),
    # 사물관리
    path("object-list/", operation_views.object_list, name="object-list"),
    re_path(
        r"^object-list/(?P<object_type>mg_id|scan_id|user_id)/$",
        operation_views.object_list,
        name="object-list-dynamic",
    ),
    re_path(
        r"^object-list/mg-id-detail/(?P<mg_id>[\w\W]+)/$",
        operation_views.mgid_detail,
        name="object-list-mg-id-detail",
    ),
    re_path(
        r"^object-list/scan-id-detail/(?P<scan_id>[\w-]+)/$",
        operation_views.scanid_detail,
        name="object-list-scan-id-detail",
    ),
    re_path(
        r"^object-list/user-id-detail/(?P<user_id>[\w-]+)/$",
        operation_views.userid_detail,
        name="object-list-user-id-detail",
    ),
    # new mg_id
    path("new-mg-id/", operation_views.new_mgid, name="new-mg-id"),
    re_path(
        r"^new-mg-id/(?P<scan_id>[\w\W]+)/$",
        operation_views.new_mgid_detail,
        name="new-mg-id-detail",
    ),
]

users/urls.py
from users import users_views
from django.urls import path, re_path

app_name = "users"

urlpatterns = [

    # Roles(Groups)
    path("authority/roles/", users_views.role_list, name="roles"),
    path("authority/roles/<int:id>", users_views.role_user_list, name="role-users"),

    path("authority/roles/role/add", users_views.role_add, name="role-add"),
    path("authority/roles/role/edit/<int:id>", users_views.role_edit, name="role-edit"),
    path("authority/roles/role/delete/<int:id>", users_views.role_delete, name="role-delete"),

    # Permissions
    path("authority/permission/", users_views.permission_list, name="permission-list"),

]

users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


class GroupExpended(models.Model):
    group = models.OneToOneField(Group, on_delete=models.CASCADE, primary_key=True)
    description = models.CharField(max_length=255, null=True, blank=True)

class CustomAccountManager(BaseUserManager):
    def create_superuser(self, email, first_name, last_name, password, **other_fields):
        other_fields.setdefault("is_staff", True)
        other_fields.setdefault("is_superuser", True)
        other_fields.setdefault("is_active", True)

        if other_fields.get("is_staff") is not True:
            raise ValueError("Superuser must be assigned to is_staff=True.")
        if other_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must be assigned to is_superuser=True.")

        super_user = self.create_user(
            email, first_name, last_name, password, **other_fields
        )

        return super_user

    def create_user(self, email, first_name, last_name, password, **other_fields):
        # email validation
        if not email:
            raise ValueError(_("You must provide an email address"))

        email = self.normalize_email(email)
        user = self.model(
            email=email, first_name=first_name, last_name=last_name, **other_fields
        )
        user.set_password(password)
        user.save()
        return user


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f"{instance.email}/{filename}"


# This is the new custom user model
class NewUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    groups = models.ManyToManyField(Group, blank=True)
    about = models.TextField(_("about"), max_length=500, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)  # this false work on ui not in admin
    division = models.CharField(max_length=150, blank=True)  # 조직
    created_at = models.DateTimeField(auto_now_add=True, null=True)  # 생성일
    # when user is created, than system send a email after varify the user we check the user is active

    objects = CustomAccountManager()

    USERNAME_FIELD = (
        "email"  # It's replace the username to email when you login in admin
    )
    REQUIRED_FIELDS = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

templates/aurora/elements/alert.html
{% if messages %}
<ul class="messages">
{% for message in messages %}
<li {% if message.tags %} class="{{ message.tags }}" {% endif %}>

    <div class="alert alert-{{ message.tags }} alert  alert-dismissible alert-alt solid fade show">
        {% comment %} {% if message.tags == 'danger' %}
        <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="me-2"><polygon points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon><line x1="15" y1="9" x2="9" y2="15"></line><line x1="9" y1="9" x2="15" y2="15"></line></svg>
         {% elif message.tags == 'success' %}
         <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="me-2"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg>
         {% elif message.tags == 'warning' %}
         <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="me-2"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line></svg>

        {% endif %} {% endcomment %}

        <div class="media">
            <div class="media-body">
                <p class="mb-0"> {{ message}}</p>
            </div>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="btn-close">
        </button>
    </div>

</li>
{% endfor %}
</ul>
{% endif %}





templates/aurora/elements/footer.html
{% load static %}

<div class="footer">
    <div class="copyright">
    </div>
</div>

templates/aurora/elements/header.html
{% load static %}
<div class="header">
    <div class="header-content">
        <nav class="navbar navbar-expand">
            <div class="collapse navbar-collapse justify-content-between">
                <div class="header-left">
                </div>
                <ul class="navbar-nav header-right">
                    <li class="nav-item dropdown header-profile">
                        <a class="nav-link" href="javascript:void(0)" role="button" data-bs-toggle="dropdown">
                            <div class="header-info">
                                <span class="text-black"><strong>{{ request.user.email }}</strong></span>
                                <p class="fs-12 mb-0">
                                    {% for g in request.user.groups.all %}
                                    {{ g.name }}
                                   {% endfor %}
                                </p>
                            </div>
                            <img id="pokemonImage" src="" alt="TODAY - Pokemon Image" width="20" style="background-color: white;">
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <a href="{% url 'aurora:user-details' id=request.user.id %}" class="dropdown-item ai-icon">
                                <svg id="icon-user1" xmlns="http://www.w3.org/2000/svg" class="text-primary" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                <span class="ms-2">Profile </span>
                            </a>
                            <a href="#" class="dropdown-item ai-icon">
                                <svg id="icon-inbox" xmlns="http://www.w3.org/2000/svg" class="text-success" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                                <span class="ms-2">Inbox </span>
                            </a>




                            <a href="{% url 'change_password' %}" class="dropdown-item ai-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" class="key text-info" viewBox="0 0 512 512" xmlns:v="https://vecta.io/nano"><path d="M334.974 0c-95.419 0-173.049 77.63-173.049 173.049 0 21.213 3.769 41.827 11.211 61.403L7.672 399.928c-2.365 2.366-3.694 5.573-3.694 8.917v90.544c0 6.965 5.646 12.611 12.611 12.611h74.616a12.61 12.61 0 0 0 8.91-3.686l25.145-25.107a12.61 12.61 0 0 0 3.701-8.925v-30.876h30.837c6.965 0 12.611-5.646 12.611-12.611v-12.36h12.361c6.964 0 12.611-5.646 12.611-12.611v-27.136h27.136c3.344 0 6.551-1.329 8.917-3.694l40.121-40.121c19.579 7.449 40.196 11.223 61.417 11.223 95.419 0 173.049-77.63 173.049-173.049S430.393 0 334.974 0zm0 320.874c-20.642 0-40.606-4.169-59.339-12.393-4.844-2.126-10.299-.956-13.871 2.525-.039.037-.077.067-.115.106l-42.354 42.354h-34.523c-6.965 0-12.611 5.646-12.611 12.611v27.136H159.8c-6.964 0-12.611 5.646-12.611 12.611v12.36h-30.838c-6.964 0-12.611 5.646-12.611 12.611v38.257l-17.753 17.725H29.202v-17.821l154.141-154.14a11.35 11.35 0 0 0 0-16.051c-4.433-4.432-11.617-4.434-16.053 0L29.202 436.854V414.07l167.696-167.708c.038-.038.067-.073.102-.11 3.482-3.569 4.656-9.024 2.53-13.872-8.216-18.732-12.38-38.695-12.38-59.33 0-81.512 66.315-147.827 147.827-147.827S482.802 91.537 482.802 173.05s-66.318 147.824-147.828 147.824zm52.664-247.73c-26.047 0-47.237 21.19-47.237 47.237s21.19 47.237 47.237 47.237 47.237-21.19 47.237-47.237-21.189-47.237-47.237-47.237zm0 69.252c-12.139 0-22.015-9.876-22.015-22.015s9.876-22.015 22.015-22.015 22.015 9.876 22.015 22.015-9.876 22.015-22.015 22.015z"/></svg>
                                <span class="ms-2">Change Password </span>
                            </a>



                            <a href="{% url 'aurora:logout' %}" class="dropdown-item ai-icon">
                                <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
                                <span class="ms-2">Logout </span>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>
<script>
    window.onload = function() {
        function padWithZeros(number, length) {
            var str = number.toString();
            while (str.length < length) {
                str = "0" + str;
            }
            return str;
        }
    
        // 1부터 1010 사이의 랜덤 숫자 생성
        var randomNum = Math.floor(Math.random() * 1010) + 1;
        
        // 자릿수를 맞춘 랜덤 Pokemon 이미지 URL 생성
        var imageUrl = `https://data1.pokemonkorea.co.kr/newdata/pokedex/full/${padWithZeros(randomNum, 4)}01.png`;
        
        // 이미지를 화면에 표시
        document.getElementById('pokemonImage').src = imageUrl;
    };
</script>

templates/aurora/elements/nav-header.html
{% load static %}
<div class="nav-header">
    <a href="{% url 'aurora:index' %}" class="brand-logo">
        <img class="logo-abbr" src="{% static 'aurora/images/logo.png' %}" alt="">
        <img class="logo-compact" src="{% static 'aurora/images/logo-text.png' %}" alt="">
        <img class="brand-title" src="{% static 'aurora/images/logo-text.png' %}" alt="">
    </a>

    <div class="nav-control">
        <div class="hamburger">
            <span class="line"></span><span class="line"></span><span class="line"></span>
        </div>
    </div>
</div>

templates/aurora/elements/sidebar.html
{% load static %}

<div class="deznav">
    <div class="deznav-scroll">
        <ul class="metismenu" id="menu">

        {% if perms.dashboard.view_dashboard %}
            <li>
                <a href="{% url 'aurora:index' %}" class="ai-icon" aria-expanded="false">
                    <i class="flaticon-381-networking"></i>
                    <span class="nav-text">Dashboard</span>
                </a>
            </li>
        {% endif %}

        {% if perms.data.view_data %}
            <li>
                <a class="has-arrow ai-icon" href="{% url 'data:svc-user-status-daily' %}" aria-expanded="false">
                    <i class="flaticon-381-database"></i><span class="nav-text">Data (지표)</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'data:svc-user-status-daily' %}">이용자 현황</a></li>
                    <li><a href="{% url 'data:scan-status-daily' %}">스캔 현황</a></li>
                </ul>
            </li>
        {% endif %}

        {% if perms.operation.view_operation %}
            <li>
                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false">
                    <i class="flaticon-381-television"></i><span class="nav-text">Operation (Admin)</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'operation:user-management' %}">이용자 관리</a></li>
                    <li><a class="has-arrow" href="{% url 'operation:object-list' %}">사물 관리</a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'operation:object-list-dynamic' object_type='mg_id' %}">mg_id</a></li>
                            <li><a href="{% url 'operation:object-list-dynamic' object_type='scan_id' %}">scan_id</a></li>
                            <li><a href="{% url 'operation:object-list-dynamic' object_type='user_id' %}">user_id</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'operation:new-mg-id' %}">new mg_id</a></li>
                    <li><a href="{% url 'operation:content-list' %}">콘텐츠 관리</a></li>
                    <li><a href="{% url 'operation:report-list' %}">신고·차단 관리</a></li>
                </ul>
            </li>
        {% endif %}

            {% if perms.users.view_newuser or perms.auth.view_group or perms.auth.view_permission %}
                <li>
                    <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false">
                        <i class="flaticon-381-user-7"></i><span class="nav-text">관리자</span>
                </a>
                    <ul aria-expanded="false">
                        {% if perms.users.view_newuser or perms.users.change_newuser or perms.users.add_newuser or perms.users.delete_newuser %}
                            <li>
                                <a  {% if '/users/' in request.path %}class="mm-active"{% endif %} href="{% url 'aurora:users' %}">Users</a>
                            </li>
                        {% endif %}

                        {% if perms.auth.view_group or perms.auth.change_group or perms.auth.add_group or perms.auth.delete_group %}
                            <li><a class="has-arrow" href="{% url 'operation:object-list' %}">권한 관리</a>
                                <ul aria-expanded="false">
                                    <li><a href="{% url 'users:roles'%}">롤 관리</a></li>
                                    <li><a href="{% url 'users:permission-list' %}">허가 관리</a></li>
                                </ul>
                            </li>
                        {% endif %}

                        {% if perms.auth.view_permission or perms.auth.change_permission or perms.auth.add_permission or  perms.auth.delete_permission%}
                            <li>
                                <a {% if '/permissions/' in request.path %}class="mm-active"{% endif %} href="{% url 'aurora:permissions' %}">Permissions</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
            {% endif %}
        </ul>
        
        <div class="copyright">
            <p><strong>aurora Arbeon Admin Dashboard</strong> © 2023 All Rights Reserved</p>
            <p>Made with <span class="heart"></span> by Arbeon</p>
        </div>
    </div>
</div>